### ISSUE TITLE
Age group breakdown in age_master.csv

### ISSUE THREAD

**Issue by kitkatbun** [Arkansascovid/Main#3]
I noticed that the age breakdown for deaths (cumulative, not new) had 2 columns for the ages 0-10 and 11-17, but that the 11-17 was NA. I wanted to verify that the 2 deaths reported in the 0-10 column were in fact 0-10 or if they were really in the 0-17 age ranged.

**Comment by amwilkins** [comment]
I just checked the raw data from the state, they're putting out NA for deaths in age range 11-17.
Can confirm from this address:
[https://services5.arcgis.com/vlhGQkz6fSnofVMD/ArcGIS/rest/services/ADH_COVID19_STATS_BY_STATE/FeatureServer/0/query?where=0%3D0&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=](https://services5.arcgis.com/vlhGQkz6fSnofVMD/ArcGIS/rest/services/ADH_COVID19_STATS_BY_STATE/FeatureServer/0/query?where=0%3D0&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=)
And searching for the attribute:  "d_age_2" : null


It looks like this is pushing both new, and cumulative death counts in that range to NA. The state has recently changed their measurements, so they may have changed their age ranges. We should follow up on that.

**Comment by Arkansascovid** [comment]
The ADH changed the reporting on these values and we will be updating the
data this week to reflect the change

**Comment by kitkatbun** [comment]
Thank you for looking into that.
