### ISSUE TITLE
Cases by Vaccination Status would be a pretty great dataset

### ISSUE THREAD

**Issue by cbellinger** [Arkansascovid/Main#4]
The fact that there are no stats on hospitalizations by vaccination status isn't doing many favors to convincing people to get shots. People need to able to show that vaccinations reduces your chances of hospitalization and death. The current datasets have no way of doing so.

**Comment by Arkansascovid** [comment]
Thanks for the comment. The ADH supplies very limited information about the hospitalizations. We will poke around in the CDC data to see if we can get some more information. Rob
